### ISSUE TITLE
Give clear license information

### ISSUE THREAD

**Issue by TheOneric** [TailsxKyuubi/inoffizielle-AoD-App#1]
README currently states:
```
This App is licensed under the terms and conditions of the BSD license
```

However, there are a multitude of licenses with BSD in their names and even more derived from such *BSD-licenses. The conditions of these licenses differs and some can even problematic, eg 4-clause BSD's advertisement clause.
As it currently stands the license is ambigous and thus it is effectively not redistributable by any third-party.

Ideally there would be a `LICENSE` file in the root dir, containing the full text and name of the used default license of the code, as well as a short license header in every source file unique to this project. Eg a short version:
```
/*
 * Copyright 2020 TailsxKyuubi
 * This code is part of inoffizielle-AoD-App and licensed under the <unambigous name of license>
 */
```
The preferred text to use in file headers varies by license.

This is very helpful if code from different projects is used and/or compiled into the binary *(which **is** already the case here)*.
It helps to figure out which license applies to each file, where it's coming from and whom to contact for eg sending in patches.
Also this way the overall license and conditions applying to the resulting binary can be determined, as this depends on **all** licenses used, so this projects license, Flutter-video-player's license and all the licenses of the other libs.

The part of the copyright notice indicating the copyright holder(s) is not strictly necessary, however many BSD-licenses contain a clause stating that redistributors `must reproduce the above copyright notice, this list of conditions and …` or similar, which only makes sense if there's some form of copyright notice.
Info about the applying license on the other hand is always good to have.

If you want to go an extra mile, you may even include info about the license of the resulting binary, which is determined by all licenses involved *(this projects license, flutter-video-player's license, license of other libs used, …)*, though as long as every file has a license users should be able to figure this out themselves without too much hassle.

---

btw, this project currently mixes English (eg README) and German (most commits and release description).
Which language is preferred for issues, etc?

**Comment by TailsxKyuubi** [comment]
Thanks for your feedback. i will add the license informations this week. as for the preferred language, i would say german. Because anime on demand is a streaming service which is only available in germany. I had created the readme back then as i started to develop the app and never modified it since then.

**Comment by TheOneric** [comment]
Thanks for addressing this so quickly.

I noticed you've chosen the 4-clause BSD license, which of course is your right to do.
Given that 4-clause BSD is rarely used today and incompatible with some other popular licenses, notably  (A|L)GPL, I just wanted to make sure this is indeed an intentional choice. This incompatibility goes both ways, so neither can \*GPL-licensed projects include any parts of this project, nor can you utilise any \*GPL-libs in this project. Also while FSF and DFSG acknowledge the BSD-4-clause as an open source license, OSI notably does **[not](https://web.archive.org/web/20091129081849/http://www.opensource.org/licenses/bsd-license.php)**.

Again, you can choose whatever license you wish for your own work and afaict BSD-4-clause is compatible with the licenses of the libs you're currently using. If you feel like the advertisement clause is apropiate and you are aware of the potential incompatibilities, then this is completely fine.

**Comment by TailsxKyuubi** [comment]
Thanks for clarifing me. I think i will switch then over to AGPL. it fullfills the criterias which are important for me,
