### ISSUE TITLE
Chromecast Support

### ISSUE THREAD

**Issue by Timwun** [TailsxKyuubi/inoffizielle-AoD-App#12]
Hey,

ein Chromecast Support wäre in der App auch noch eine super Sache, hoffentlich mit besserer Anbindung als die von AoD selbst (Wenn du dazu technischen Hintergrund brauchst, hook me up.)

**Comment by TailsxKyuubi** [comment]
Für mich ist der Chromecast noch komplett unbekannt. Daher kann ich nichts direkt dazu sagen. Die Umsetzung für den Android TV gestaltet sich teilweise schon schwierig. Daher würde ich das erstmal hinten anstellen.

**Comment by Timwun** [comment]
Kein Thema, nach meinem Wissen funktioniert der Chromecast anders als Android TV. An den Chromecast schickt man eigentlich nur woher das Video kommt (z.B. Link) und er zeigt das dann an. :)

Aber hat keine Eile! :)

**Comment by TailsxKyuubi** [comment]
Mir ist grade noch eingefallen, dass 1080p und 1080p+ laut AoD Probleme auf dem Chromecast hat. Von dem Punkt her macht da Chromecast support überhaupt sinn wenn maximal nur 720p möglich sind?

**Comment by Timwun** [comment]
Laut Google selbst kann der Chromecast (zumindest die 3. Generator) 1080p60 und die anderen 1080p30. Ich persönlich kann dir aber sagen, dass 720p60 am Besten funktioniert. Ich gucke z.B. nur über Chromecast. Über die App müsste ich eben nicht mehr dauerend den Laptop dafür anhaben um Serien zu gucken. :)

**Comment by TailsxKyuubi** [comment]
Da geht es nicht um 1080p an sondern, dass AoD für 1080p und 1080p+ spezielle Settings für den Encode verwendet, die nicht unbedingt von allen Geräten unterstützt werden. Besonders betroffen sind / waren Fernseher und Chromecast. Bei Mobilen geräten und PC ist das schon länger kein Problem mehr

**Comment by TailsxKyuubi** [comment]
Du kannst gerne nachprüfen ob der Chromecast die qualitätsstufen 1080p und 1080p+ bei aod abspielen kann. Falls nicht würde ich die frage stellen ob es sich überhaupt lohnt da 720p streams auf dem fernseher laufen zu lassen

**Comment by Timwun** [comment]
Hey, da Netflix & co auch alle nur auf 720p auf einem Chromecast gucken und es doch anschaubar ist, lohnt es sich schon. Besonders, weil ein Chromecast explicit ausgelegt ist, mit dem Handy bedient zu werden. 

Ich werde mich ab gerne mal ein wenig reinlesen. Dart sieht jetzt als Programmiersprache nicht all so schwer aus.

**Comment by TailsxKyuubi** [comment]
Wenn du über dein Handy das Video auf den Chromecast streamst macht es wiederum sinn, da der handys 1080p und 1080p+ können.

**Comment by Timwun** [comment]
Meinst du Screensharing vom Smartphone auf Chromecast? Falls ja, das klappt nicht gut. Audio ist hinter Video und die Videos sind komprimiert. 

Sonst nochmal eine kleine Erklärung wie ein Chromecast funktioniert: 

1. Smartphone sendet Codesnippet an Chromecast (Chromecast App)
2. Chromecast für das Codesnippet aus
3. Video wird abgespielt

Angeblich kann der Chromecast auch 1080p60, aber das spricht gegen meine Erfahrungen. [Siehe hier](https://store.google.com/de/product/chromecast_specs)
Werde die Tage aber nochmal ein anderen Monitor testen.

Hab auch eben eine kleine Recherche über Dart & Chromecast Support gemacht [Siehe hier](https://github.com/terrabythia/flutter_chromecast_example), sieht wohl alles gut Dokumentiert und supportet aus. Ich werde mich Mal am Wochenende dran machen und gucken ob ich das vielleicht selbst hinbekomme. Aber verlass dich da lieber nicht drauf! :D

**Comment by TailsxKyuubi** [comment]
Ok, ich hab mir das grob mal angeschaut. Sieht mir jetzt nicht allzu kompliziert aus. Wenn du was machen willst, dann am besten auf basis des 0.8 branches. der master und android tv sind grade nicht dafür geeignet

**Comment by ghost** [comment]
> Ok, ich hab mir das grob mal angeschaut. Sieht mir jetzt nicht allzu kompliziert aus. Wenn du was machen willst, dann am besten auf basis des 0.8 branches. der master und android tv sind grade nicht dafür geeignet

Hast du den schon ne Android TV App angefangen? Falls ja würde ich sie schon ausprobieren wollen. Ich kann's nämlich nicht abwarten auf meinem fehrnsehr Anime in 4k schauen zu können.

**Comment by TailsxKyuubi** [comment]
> Hast du den schon ne Android TV App angefangen? Falls ja würde ich sie schon ausprobieren wollen. Ich kann's nämlich nicht abwarten auf meinem fehrnsehr Anime in 4k schauen zu können.

ja aber die ergebnisse lassen bisher noch zu wünschen übrig. Sobald ich eine stabile version habe wird diese als vorabversion veröffentlicht

**Comment by ghost** [comment]
> > Hast du den schon ne Android TV App angefangen? Falls ja würde ich sie schon ausprobieren wollen. Ich kann's nämlich nicht abwarten auf meinem fehrnsehr Anime in 4k schauen zu können.
> 
> ja aber die ergebnisse lassen bisher noch zu wünschen übrig. Sobald ich eine stabile version habe wird diese als vorabversion veröffentlicht

Nice bin schon gespannt.

**Comment by TailsxKyuubi** [comment]
@Timwun Da das Thema um die Android TV Version nahezu komplett durch ist, wäre für die Version 0.9 Chromecast Support möglich

**Comment by TailsxKyuubi** [comment]
@Timwun

**Comment by TailsxKyuubi** [comment]
Wurde geschlossen, da keine Antwort
