### ISSUE TITLE
Player fehler

### ISSUE THREAD

**Issue by ghost** [TailsxKyuubi/inoffizielle-AoD-App#13]
Hallo ich wollte nur sagen das im Player das Video asynchron wiedergegeben wird also das Video hängt hinter dem Ton hinterher und es lässt sich leider nicht beheben.

**Comment by TailsxKyuubi** [comment]
Kannst du mehr Details zu diesem Fehler geben, ansonsten kann ich schwer herausfinden woran das bei dir liegt

**Comment by ghost** [comment]
Also ich habe ein Video vorgespult und dann war das Video immer asynchron und es konnte durch ein Neustart der App oder des Videos nicht behoben werden es könnte allgemein am vorspulen liegen aber mehr weiß ich leider auch nicht.

**Comment by TailsxKyuubi** [comment]
Welches Gerät? Welche Android Version? Welche App version?
Das alles kann einen Einfluss darauf haben und mir dabei helfen das Problem zu finden

**Comment by ghost** [comment]
Gerät: Honor 9x Pro
Android Ver.: 9.1.1
App Ver.: 0.7.1

**Comment by TailsxKyuubi** [comment]
Welche Serie / Film mit welcher Qualitätseinstellung in der App tritt das auf?

**Comment by ghost** [comment]
Du kannst es ja selbst Mal ausprobieren also bei mir ist der Fehler in der 2en Folge von food wars season 1 vorgekommen schau dir das Video so 1 bis 2 min. An und dann überspringe Mal 10 sek. 30sek. Wenn bis dahin der Fehler nicht aufgetaucht ist benutze die Video Fortschritt Leiste und bewege sie ein wenig.

**Comment by ghost** [comment]
> Welche Serie / Film mit welcher Qualitätseinstellung in der App tritt das auf?

720p und ja in der App.

**Comment by ghost** [comment]
> Du kannst es ja selbst Mal ausprobieren also bei mir ist der Fehler in der 2en Folge von food wars season 1 vorgekommen schau dir das Video so 1 bis 2 min. An und dann überspringe Mal 10 sek. 30sek. Wenn bis dahin der Fehler nicht aufgetaucht ist benutze die Video Fortschritt Leiste und bewege sie ein wenig.

Hab's korrigiert es ist food wars nicht good war. Sry

**Comment by TailsxKyuubi** [comment]
> Hab's korrigiert es ist food wars nicht good war. Sry

Was meinst du damit?

**Comment by ghost** [comment]
> > Hab's korrigiert es ist food wars nicht good war. Sry
> 
> Was meinst du damit?

Ich hatte erstmal ausversehen (Anime Name) good war geschrieben dabei meinte ich food wars.

**Comment by ghost** [comment]
Wäre das OK für dich über Twitter zu schreiben weil ich würde dir gerne einen Vorschlag machen weil du ja nicht weißt wie du das mit dem folgen Fortschritt im Startmenü am besten optisch gut darstellen kannst.

**Comment by TailsxKyuubi** [comment]
Ich konnte diesen Fehler in der aktuellen Entwicklerversion jetzt nicht direkt nachstellen, mit dem Player. Alles was explizit die Entwicklung der App betrifft, kommt bitte hier alles auf Github. Du kannst dafür ein eigenes Issue aufmachen mit den Vorschlag

**Comment by TailsxKyuubi** [comment]
@S0T0N0 Irgendeine Veränderung diesbezüglich?

**Comment by S0T0N0** [comment]
Es war kein Fehler der App sondern ein Fehler meiner seits.

**Comment by ghost** [comment]
Ich habe gemerkt das dieser Fehler auftaucht wenn man im Player auf Pause drückt und dann nach ca. 1 min. Auf Play drückt auftaucht, ich vermute das nur das Video angehalten wird aber nicht die Ton Spur hört sich zwar bescheuert an aber erscheint mir ein wenig plausibel.

**Comment by ghost** [comment]
Hier ein Video da sieht man das dass Video asynchron ist. Ich entschuldige mich schonmal im voraus für die Hintergrundgeräusche. https://youtu.be/2Dx82ijem2o

**Comment by TailsxKyuubi** [comment]
Ich vermute, dass das eventuell ein Bug in der Player abhängigkeit ist. Ich wollte da eigentlich, warten bis die Entwickler das nächste Update in die Dart Paketverwaltung reinhauen (wegen einem anderen Bug den die drin hatten), aber es wäre wohl besser das in der hinsicht selbst mal zu aktualisieren

**Comment by ghost** [comment]
> Ich vermute, dass das eventuell ein Bug in der Player abhängigkeit ist. Ich wollte da eigentlich, warten bis die Entwickler das nächste Update in die Dart Paketverwaltung reinhauen (wegen einem anderen Bug den die drin hatten), aber es wäre wohl besser das in der hinsicht selbst mal zu aktualisieren

Was für einen Player verwendest du denn?

**Comment by TailsxKyuubi** [comment]
Wenn ich dir eine Vorabversion schicke, könntest du das dann testen ob der bug behoben wurde?

**Comment by TailsxKyuubi** [comment]
Intern baut das alles auf dem exoplayer auf

**Comment by ghost** [comment]
> Wenn ich dir eine Vorabversion schicke, könntest du das dann testen ob der bug behoben wurde?

Ja

**Comment by ghost** [comment]
https://github.com/google/ExoPlayer/releases benutzt du den hier?

**Comment by TailsxKyuubi** [comment]
An sich baut das was ich benutze darauf auf https://pub.dev/packages/video_player auf. Dieser benutzt intern Exoplayer für android und avplayer für iOS

**Comment by ghost** [comment]
Also ich sage dir nur eins ich verstehe nicht viel davon was App programmieren angeht und was das generelle programmieren angeht ich bin nur gut im Fehler finden und ich bin Recht geschickt mit Design Programmen, also falls du was in der Richtung für mich zu tun hast immer her damit aber das mit dem Player Must wohl oder übel doch alleine machen. Tut mir leid.

**Comment by TailsxKyuubi** [comment]
ich versuche einfach mal den player zu updaten und mal schauen ob das, das problem löst

**Comment by ghost** [comment]
> ich versuche einfach mal den player zu updaten und mal schauen ob das, das problem löst

Ja das wäre eine Lösung sonst könnte man auch einen anderen Player versuchen.

**Comment by TailsxKyuubi** [comment]
Das wäre mit sehr großem aufwand verbunden. vergleichbar mit dem TV Support

**Comment by ghost** [comment]
> Das wäre mit sehr großem aufwand verbunden. vergleichbar mit dem TV Support

OK wie gesagt ich verstehe davon nicht viel.

**Comment by ghost** [comment]
> Das wäre mit sehr großem aufwand verbunden. vergleichbar mit dem TV Support

Falls du mir es erklärst könnte ich mich Mal daran versuchen ich hatte Mal ein Praktikum bei einer programmier Firma und habe ähnliche Sachen gemacht also ein wenig verstehe ich was davon.

**Comment by TailsxKyuubi** [comment]
Für den TV Support habe ich glaube schon ne dreistellige Anzahl an Stunden investiert mit rumprobieren, wie das am besten funktioniert

**Comment by ghost** [comment]
Welche ver. Benutzt du momentan?

**Comment by TailsxKyuubi** [comment]
Ich benutze von der library eine modifizierte version 0.11.1+2
da ist eigentlich noch der Buffering bug drin und wird erst mit der Version 1.0.2 da richtig behoben sein (welche noch nicht richtig erschienen ist)

**Comment by ghost** [comment]
Welches Programm benutzt du für die Programmierung der App?

**Comment by TailsxKyuubi** [comment]
intellij idea mit dem flutter plugin

**Comment by ghost** [comment]
> intellij idea mit dem flutter plugin

Comunity oder ultimate?

**Comment by TailsxKyuubi** [comment]
Community

**Comment by ghost** [comment]
Du kannst mir ja schonmal eine Beta ver. Schicken von deiner aod App mit der neuen Player ver. Dann kann ich schauen ob der Fehler dann nicht mehr da ist.

**Comment by TailsxKyuubi** [comment]
ja werde die dann im laufe der nächsten woche erstellen

**Comment by ghost** [comment]
> ja werde die dann im laufe der nächsten woche erstellen

OK du kannst mir die App dann über Twitter schicke als Media fire link.

https://mobile.twitter.com/SOTONO324/

**Comment by TailsxKyuubi** [comment]
Ich werde die hier auf github hochladen

**Comment by ghost** [comment]
> Ich werde die hier auf github hochladen

Ok

**Comment by TailsxKyuubi** [comment]
Hier ist die Version mit dem aktualisierten Player. Nicht wundern wenn der Ladekreis beim nachladen des Videos nicht kommt. Falls der Bug dann bei dir nicht mehr auftaucht werde ich das manuell nachfixen.
[app.apk.zip](https://github.com/TailsxKyuubi/inoffizielle-AoD-App/files/6045576/app.apk.zip)

**Comment by ghost** [comment]
Hab's ausprobiert der Fehler scheint behoben.
