### ISSUE TITLE
Lautstärke Regler Entfernung.

### ISSUE THREAD

**Issue by ghost** [TailsxKyuubi/inoffizielle-AoD-App#15]
Ich weiß nicht ob in dieser Funktion viel Arbeit steckte aber ich würde dir empfehlen sie zu entfernen den sie regelt nicht die Audio Lautstärke des Handys sondern die Lautstärke der App soll heißen daß es rein theoretisch total unnütz ist außer du änderst das so das die Handy Lautstärke verändert wird.

**Comment by TailsxKyuubi** [comment]
Der wird deaktivierbar und der wird auch soweit verbessert, dass der nicht mehr so ganz empfindlich ist
