### ISSUE TITLE
Folge/Film Fortschritt merken Fehler.

### ISSUE THREAD

**Issue by ghost** [TailsxKyuubi/inoffizielle-AoD-App#16]
Hi ich bin's Mal wieder mit den fehlern, ein Fehler der mir auch aufgefallen ist, ist das der Fortschritt für folgen oder Filme nicht richtig gespeichert wird also wenn man in der App ist kurz aus einer Folge oder Film raus geht und wieder rein dann wird das am letzten Punkt wieder gegeben also das klappt aber wenn man die App komplett schließt dann ist der Fortschritt verloren.

**Comment by TailsxKyuubi** [comment]
Ich habe mal einen Testfix erstellt. Die Apk ist unter folgendem Link herunterladbar:
https://git.tailsxkyuubi.moe/tailsxkyuubi/inoffizielle-AoD-App/-/jobs/53/artifacts/raw/build/app/outputs/flutter-apk/app-release.apk
Ich werde persönlich den Fix über die Tage auch testen und genaueres dann sagen können.

**Comment by TailsxKyuubi** [comment]
Bin auf eine andere Stelle im Code gekommen die höchstwahrscheinlich dafür verantwortlich ist. Werde die Stelle heute noch fixen

**Comment by TailsxKyuubi** [comment]
Die neue Apk ist unter folgendem link herunterladbar:
https://git.tailsxkyuubi.moe/tailsxkyuubi/inoffizielle-AoD-App/-/jobs/5/artifacts/raw/build/app/outputs/flutter-apk/app-release.apk
