### ISSUE TITLE
Vollbild auf Fire TV 

### ISSUE THREAD

**Issue by GOW2017** [TailsxKyuubi/inoffizielle-AoD-App#18]
hey, hab die App auf dem Fire TV stick getestet und dort nimmt der Stream nur etwas mehr als ein Viertel des Bildes ein. Der Rest läuft wie ne 1

**Comment by TailsxKyuubi** [comment]
Kannst du bitte ein Bild posten wie das aussieht, sowie auch die auflösung deines Fernsehers

**Comment by GOW2017** [comment]
![20210308_212433](https://user-images.githubusercontent.com/80264194/110377634-f02cad00-8054-11eb-9dc2-e00ad98af94f.jpg)

Auflösung vom Fernseher ist UHD. Hab den Stick Mal auf 1080p gestellt, kommt aber das gleiche bei heraus.

**Comment by TailsxKyuubi** [comment]
War der Ladebildschirm vom Player noch Vollbild? Wenn ja habe ich einen möglich Fix. Der würde dann in die nächste TV Alpha Version reinkommen.

**Comment by GOW2017** [comment]
Ja der ist noch Vollbild

**Comment by GOW2017** [comment]
Mir ist noch was aufgefallen weiß aber nicht ob das noch so sein soll. Im Player ist keine Zeitleiste und man kann nicht stoppen. Vor- und zurückspulen funktioniert aber. 

Hat sich geklärt.

**Comment by TailsxKyuubi** [comment]
> Mir ist noch was aufgefallen weiß aber nicht ob das noch so sein soll. Im Player ist keine Zeitleiste und man kann nicht stoppen. Vor- und zurückspulen funktioniert aber.

Meines Wissens nach hat der FireTV Stick eine Knopf auf der Fernbedinung zum Pausieren und Starten des Videos. Auf die taste wurde das gelegt. Es gibt eine Zeitleiste die aufgrund des ganzen Grüns auf dem fernseher nicht sichtbar sein wird und in den Einstellungen aktiviert werden muss. Hintergrund wieso das explizit aktiviert werden muss, ist ganz einfach weil das die Leute auf dem Smartphone gestört hatte und es ist deswegen standardmäßig aus

**Comment by TailsxKyuubi** [comment]
Am Wochenende wird ein Update rauskommen, bei dem du testen kannst, ob der Vollbild Bug behoben ist. Ich habe leider keinen FireTV Stick zur Verfügung und kann das daher nicht direkt testen.

**Comment by Letsplaybar** [comment]
was für ne Auflösung hast du in den Einstellungen auf der Seite eingestellt? 

![image](https://user-images.githubusercontent.com/20257680/110972626-79492a00-835c-11eb-9ce8-cd88f5132575.png)

**Comment by TailsxKyuubi** [comment]
@GOW2017 kannst du bitte überprüfen ob das problem in der neuen version gelöst ist?

**Comment by GOW2017** [comment]
Hi, ist leider noch das gleiche mit dem Vollbild. Hab es auch mit jeder Auflösung versucht, sieht aber immer noch so aus wie vorher.

**Comment by GOW2017** [comment]
![20210314_032837](https://user-images.githubusercontent.com/80264194/111055397-c1a83b00-8475-11eb-8afb-f17d5a3835bb.jpg)
![20210314_032927](https://user-images.githubusercontent.com/80264194/111055402-c5d45880-8475-11eb-9e00-e1d3ad2f359f.jpg)
![20210314_032936](https://user-images.githubusercontent.com/80264194/111055403-ca007600-8475-11eb-94ff-4d0f27fb2c93.jpg)

**Comment by GOW2017** [comment]
Hab jetzt mal alles fotografiert von Streamatart bis zum halb Vollbild. Vielleicht hilft die Info, dass das Bild Anfangs ganz klein ist und erst nach 5-10 Sekunden größer wird. Habe eine Folge auch bereits durchlaufen lassen um zu schauen, ob sich das Bild nochmal vergrößert und vielleicht den kompletten Bildschirm einnimmt, aber so wie es auf dem letzen Bild ist, bleibt es bis zum Ende.

**Comment by GOW2017** [comment]
Dass das Bild zu Beginn nur so ausgefüllt ist, wie beim 2. Bild, kommt übrigens nur bei 360p, 480p, 576p und 1080p+ vor. Der Rest startet direkt wie auf dem 3. Bild.

**Comment by TailsxKyuubi** [comment]
Dank der zusätzlichen Infos weiß ich nun was schief läuft, aber noch nicht warum. Ich habe eine Idee, wie man das Problem mit etwas Glück beheben kann. Ich werde dafür dann hier in dem Issue eine Version bereitstellen.

**Comment by TailsxKyuubi** [comment]
Hier ist eine Version bei der ich hoffe, dass das Problem gelöst ist: 
[app.zip](https://github.com/TailsxKyuubi/inoffizielle-AoD-App/files/6136220/app.zip)

**Comment by GOW2017** [comment]
Leider immernoch wie vorher

**Comment by TailsxKyuubi** [comment]
So ich habe nun eine Version auf meinen Webserver hochgeladen, bei der die Entwicklertools noch enthalten sind. Der grüne Hintergrund müsste sich dann in Rot verwandeln und eine Fehlermeldung in weißer Schrift anzeigen. Diese bräuchte ich um dem Fehler auf den Grundzu gehen. Der Link zur Datei (Github mag keine großen Dateien in den Issues)
https://tailsxkyuubi.moe/app-debug.apk

**Comment by GOW2017** [comment]
Ich bekomme die Datei nicht installiert, da sie nicht kompatibel zu sein scheint.

**Comment by TailsxKyuubi** [comment]
Mal eine andere Frage zu dem problem: kannst du mal ein foto deiner fernbedienung machen, damit wir das modell deines Sticks bestätigen können?

**Comment by GOW2017** [comment]
![20210314_165443](https://user-images.githubusercontent.com/80264194/111074987-feac1600-84e5-11eb-89ec-f3d149554501.jpg)

**Comment by Letsplaybar** [comment]
welche Version vom Firetv hast du? (Jahrgang) und hast du den Stick gerootet?

**Comment by GOW2017** [comment]
Die 4k Version, davon gibt es glaube ich nur eine. 
Ist nicht gerootet

**Comment by GOW2017** [comment]
![20210314_165607](https://user-images.githubusercontent.com/80264194/111075152-ef799800-84e6-11eb-84b4-6d21572c0ddf.jpg)

Vielleicht hilft das

**Comment by Letsplaybar** [comment]
neh gibt die 2019 er und die 2020 er Version aber hast mal nach Updates gesucht? bei mir ist das ganze schon auf Fire OS 7.2.2.9 (PS7229/1853)

**Comment by GOW2017** [comment]
Alles klar es liegt am 4K Stick bzw. an seiner Version. 
Fire OS 7 gibt es nämlich nur für den Stick Lite und den normalen 2020er Stick, zum Glück habe ich den 2020er Stick nämlich auch Zuhause und hab dort einfach Mal jetzt die App Version von heute Nacht draufgeladen und wenig überraschend ist dort das gesamte Bild ausgefüllt. 

Der 4K Stick ist nicht aktuell genug und es ist auch unklar ob er jemals das Fire OS 7 Update bekommt (hatte mit Amazon gechattet und da ist es wohl wahrscheinlicher, dass die einen komplett neuen 4K Stick rausbringen werden, da es auch tatsächlich bisher nur einen gibt)

**Comment by Letsplaybar** [comment]
hm mir fällt grade auf das im Ticket #19 hat jemand das ganze aber auch auf den 4k Stick (2019) installiert und hat das Problem nicht, interessant, sicher das du nicht nen update machen kannst? Bei mir auf dem Cube (4K) hats jedenfalls ohne Probleme funktioniert.

**Comment by GOW2017** [comment]
Ja, die Mitarbeiterin meinte auch, dass ich die aktuellste Version für den Stick habe. Cube ist denke ich mal dann wohl eine andere Geschichte.

**Comment by Letsplaybar** [comment]
https://www.netzwelt.de/news/181519-amazon-fire-tv-4k-cube-erhalten-gross-update-maerz.html laut dem Artikel sollen die 4k eigentlich ab März auch das update bekommen Hm.

**Comment by GOW2017** [comment]
Hmm, kann ja auch nur das widergeben, was mir die Mitarbeiterin erzählt hat 😅. Dann hoffe ich einfach mal, werde es ja sehen.

**Comment by TailsxKyuubi** [comment]
In der nächsten Version wird dann ein Warnhinweis eingeblendet der darauf hinweist, dass Fire OS 6 nicht offiziell unterstützt wird.

**Comment by abcboy75** [comment]
Ich habe den Fire TV Stick 4K und aktuell ist die Version FireOS 6.2.7.7 (NS6277/3033) installiert.
Ich denke mal das dass neue Update noch kommen wird. 

Ich habe auch den Full Screen Bug.

**Comment by TailsxKyuubi** [comment]
Der Versionscheck ist implementiert
