### ISSUE TITLE
Fire Tv steuerung probleme

### ISSUE THREAD

**Issue by KILLERsandwich** [TailsxKyuubi/inoffizielle-AoD-App#19]
Hi ich bins ma wieder ich habe festgestellt das es immernoch schwierigkeiten mit der steuerung gibts ich habe versucht so gut es gegt das problem zu replitzieren das bei meinem fire-tv stick 4k auftritt.
Unzwar tritt diese problematik auf wenn ich auf den reiter animes gehe dort kann ich auch die tasten benutzen das funktioniert allerdings habe ich festgestellt das die steuerung irgendwann wieder nach ganz oben auf die suchleiste springt wenn ich versuche nach ganzunten durchzugehen und sobald das passiert kann ich nicht mehr auf die reiter unten am rand gehen und die steuerung setzt danch auch aus wenn ich auf einen anime gehe ist in dem fall dan egal welcher ich kann dan nichtmehr steuern.
Das gleiche problem tritt auf wenn ich von anfang auf einen anime gehe und durch die episoden navigiere das funktioniert gut bis zu dem moment an dem ich die zurück taste auf der verbedienung benutze danach ist wieder das gleiche problem ich muss also immer oben links auf die zurück taste navigieren.
Ich mache demnächst ein video davon damit man es besser sehen kann was ich meine hoffentlich hilft diese info was bug fixing angeht und ich habe noch dazu ebenfals das problem festgestellt mit dem player das das bild mini ist und der rest ist grün allerdings ist das problem weg sobald man einmal kurz die spultaste betätigt dan ist es wieder vollbild.
Leider lässt sich die leiste nicht anzeigen wie weit die episode bereits ist :/ hab zumindest nicht rausgefunden wie aber spulen, stopp, und fortsetzen funktioniert top. 👍

**Comment by Letsplaybar** [comment]
das mit der Suchleiste das ich darauf springe hab ich auch aber danach kann ich dann ohne Probleme ganz normal navigieren. die anderen Probleme hab ich bei meinen Gerät nicht 4k (sowohl Fernseher als auch der Cube) was für ne Auflösung hast du in den Einstellungen ausgewählt? 1080p+?

Also auf der Seite:
![image](https://user-images.githubusercontent.com/20257680/110972371-36875200-835c-11eb-982c-9b0ee1ee7ca5.png)

**Comment by KILLERsandwich** [comment]
Habe auf 1080p gestellt und das mit dem das man den fortschrittsbalken nicht sieht nehme ich zurück man siet sie jetzt leider halt permanent wär nice wenn sie irgendwann wegfaded und hier wie versprochen der link zu einem video von der problematik

https://mega.nz/file/1BtA1baY#r7ErDb7n8XzGU-enrut5w6tZFjkqK7XQGUNd1r0Twew

**Comment by TailsxKyuubi** [comment]
Es gibt in den Einstellungen die Option Fortschritt immer anzeigen. Diese blendet einen Fortschrittsbalken unten ein.
Die Leute hatte der genervt und wurde deswegen standardmäßig deaktiviert, ist aber noch als Option verfügbar.
Ich bin mir nur nicht wie gut der auf dem TV zu sehen ist

**Comment by KILLERsandwich** [comment]
Alles klar deswegen wird der bei mir angezeigt hatte die option eingeschaltet weil ich dachte vieleicht ändert das was an der steuerung 😂 zumindest wissen wir jetzt das der funktioniert wie er soll

**Comment by TailsxKyuubi** [comment]
Wollte nochmal da noch etwas eine abspeckte Version vom der Bedienelemente des Smartphones einbauen, aber da fehlen mir leider noch ein paar Infos um das richtig umsetzen zu können

**Comment by Letsplaybar** [comment]
hab mir dein Video angeschaut und es mal selbst nach probiert, sobald ich das Suchenfeld bedient habe bugt das ganze und ich kann sogar out of border gehen und verliere die Steuerbarkeit ganz aber selbst wenn ich noch einen Fokus auf einen Element habe kann ich nicht mehr enter drücken. Der Rest ist aber wirklich mehr als Komisch, das funktioniert bei mir ohne Probleme. Welche Version vom Stick hast du (also Produktionsjahr)

**Comment by KILLERsandwich** [comment]
Habs 2019 gekauft den 4k stick

**Comment by Letsplaybar** [comment]
hm hab auch den 2019er und ich habe nur nen teil der Probleme auf meinem Cube und denke mal nicht das da beim Stick was anders abläuft als beim Cube hab jedenfalls kein Unterschied festgestellt.

**Comment by TailsxKyuubi** [comment]
Habe mir das Video angeschaut und kenne die Ursache in der Animeübersicht. Das ist was das Framework selber an Steuerung vorgibt. Das werde ich noch überschreiben. genau die Steuerung überschreiben mache ich grade für die Startseite

**Comment by TailsxKyuubi** [comment]
Ist im Android TV branch schon gefixt. Wird spätestens morgen in den master gemergt und die neue Version releast

**Comment by TailsxKyuubi** [comment]
Bitte um Bestätigung, dass das Problem gelöst ist

**Comment by ghost** [comment]
Das Problem ist gelöst aber jetzt gibt es ein neues man kann nur noch auf der Startseite Steuern wenn man auf Anime oder Einstellungen will klappt das nicht.

**Comment by TailsxKyuubi** [comment]
Dafür gibt es die Menü Taste

**Comment by ghost** [comment]
Welche Menü taste?

**Comment by TailsxKyuubi** [comment]
![mceclip1](https://user-images.githubusercontent.com/65784417/111061200-65a7db80-84a2-11eb-8f10-b3df69b1426f.png)

**Comment by ghost** [comment]
Achso ich rede von Android tv lul

**Comment by TailsxKyuubi** [comment]
Ich müsste wissen wie deine fernbedienung aussieht um genaueres sagen zu können

**Comment by ghost** [comment]
![IMG_20210314_085702.jpg](https://user-images.githubusercontent.com/72794819/111061369-4d848c00-84a3-11eb-98de-f0ab77cae570.jpg)

Kreis: Home
9 Blöcke: Alle Apps
Pfeil: Zurück

Der Rest ist wie bei der fire tv Fernbedienung.

**Comment by TailsxKyuubi** [comment]
Ok ich bin eher geschockt, wie wenig der wo die Fernbedienung designed hat, über die Möglichkeiten von Android TV bescheid wusste

**Comment by TailsxKyuubi** [comment]
@S0T0N0 ich habe mir das ganze mal angeschaut und kann leider für die China billigware nicht vollen Support bieten, da die das auf anderen geräten Probleme machen kann, nur weil diese an ein paar Tasten gespart haben. Für das Menü werde ich eine Möglichkeit einbauen das ohne die Menütaste zu benutzen. Im Player wird es allerdings keine Anpassungen für den Xiaomi Stick geben.

**Comment by Letsplaybar** [comment]
@KILLERsandwich welche FireOS  Version hast du auf deinen 4k Stick? ist relevant für das verlinkte Ticket.

**Comment by ghost** [comment]
> @S0T0N0 ich habe mir das ganze mal angeschaut und kann leider für die China billigware nicht vollen Support bieten, da die das auf anderen geräten Probleme machen kann, nur weil diese an ein paar Tasten gespart haben. Für das Menü werde ich eine Möglichkeit einbauen das ohne die Menütaste zu benutzen. Im Player wird es allerdings keine Anpassungen für den Xiaomi Stick geben.

Ich habe die MiboxS nicht den Stick.

**Comment by TailsxKyuubi** [comment]
Das macht leider keinen Unterschied, da die Fernbedienung dieselbe ist und die hat nichmal alle Standardtasten für nen Stick / Box der Streaming unterstützen soll.

**Comment by ghost** [comment]
> Das macht leider keinen Unterschied, da die Fernbedienung dieselbe ist und die hat nichmal alle Standardtasten für nen Stick / Box der Streaming unterstützen soll.

Naja Pause/vorspulen/Zurückspulen hat die Fernbedienung jetzt nicht aber es kommt ja auch auf das Betriebssystem an den der fire tv stick benutzt zwar Android aber eine modifizierte Version die von Amazon erstellt wurde, deswegen kann man ja nicht erwarten das dass mit dem Menü button auch auf Standard Android tv Boxen/Sticks funktioniert.

**Comment by Letsplaybar** [comment]
deshalb hat er ja auch gesagt das er das mit dem menu auch noch anders hinzufügen wird halt nur nicht mit der play taste bzw vor zurück spulen. Diese haben die Standard AndroidTV Fernseher nämlich und das Funktioniert auch Super

**Comment by KILLERsandwich** [comment]
Habe soweit ich weis die neuste version von fireos 
Also bei mir funktioniert die steuerung jezt sehr gut mit der neuen version das einzige problem is nur das die app sich halt manchmal aufhängt aber ich glaube das ist einfach dem arbeitschpeicher des 4k sticks geschuldet

**Comment by ghost** [comment]
> deshalb hat er ja auch gesagt das er das mit dem menu auch noch anders hinzufügen wird halt nur nicht mit der play taste bzw vor zurück spulen. Diese haben die Standard AndroidTV Fernseher nämlich und das Funktioniert auch Super

Ich weiß, ich habe ihn ja nur drauf hinweisen.

**Comment by TailsxKyuubi** [comment]
Habe grade nochmal die Änderungen an der Steuerung gemacht. Ein neues Release gibts spätestens am Freitag.
