### ISSUE TITLE
Android tv app Absturz

### ISSUE THREAD

**Issue by ghost** [TailsxKyuubi/inoffizielle-AoD-App#26]
Die App stürzt warum auch immer wenn ich einen Anime schaue ab.

**Comment by TailsxKyuubi** [comment]
Kannst du bitte dazu mehr infos geben? Weil so ist das sonst wie das Suchen einer Nadel im Heuberg

**Comment by ghost** [comment]
So kannst du es auch sehen den ich weiß selbst nicht viel die App ist einfach abgestürzt nachdem ich Beenden erzwingen und den Cache geleert habe hat's wieder funktioniert.

**Comment by TailsxKyuubi** [comment]
Vermutlich das gleiche Problem #27

**Comment by ghost** [comment]
> Vermutlich das gleiche Problem #27 

Ja scheint mir auch so gucke gerade Dragon Quest und es ist bis jetzt nichts passiert.

**Comment by TailsxKyuubi** [comment]
Dann kann das hier geschlossen werden?
