### ISSUE TITLE
Android TV Stream kann nicht wiedergegeben werden

### ISSUE THREAD

**Issue by z8ckerbestie** [TailsxKyuubi/inoffizielle-AoD-App#27]
Hey Ho,
ich bin auf die App aufmerksam geworden und benutze sie mit einem Philipps OLED 804 (Android TV  9). Aktuell ist es bei mir aber so, dass nach jeder Folge der Stream abbricht und ich nur noch "Stream beenden" oder "Stream neustarten" kann. Bei letzterem landet man dann aber in einer Endlosschleife.
App beenden und / oder Cache löschen hilft, danach geht es wieder, leider aber auch immer nur für eine Folge.

![IMG_20210320_214550](https://user-images.githubusercontent.com/81047238/111885113-fceec080-89c5-11eb-963d-ac7185d466c7.jpg)

**Comment by TailsxKyuubi** [comment]
Welche Qualität hast du im Stream ausgewählt?  was wolltest du abspielen?

**Comment by Letsplaybar** [comment]
Fehler ist auch auf dem Smartphone vorhanden (vermute Vollgelaufener Ram) nach abwarten einiger Zeit klappt das abspielen auch ohne beenden wieder, da vermutlich der garbage Collector drüber gelaufen ist. 

Hast du die eine Folge geskipt? Oder regulär laufen lassen.

**Comment by z8ckerbestie** [comment]
Ich hab 1080p+ ausgewählt und schaue gerade My Hero Academia (Staffel 1), Fehler tritt aber auch bei anderen Serien auf. Ich kann es aber Mal mit einer anderen Qualität versuchen.

Und nein, nichts geskippt oder vorgespult. Ich warte einfach Mal etwas ab, ob es dann von allein weiter läuft.

**Comment by Letsplaybar** [comment]
von alleine wird da mit dem Fehler nix passieren, nach ner weile dürfte aber wenn du auf neu starten drückst dies wieder funktionieren.

**Comment by z8ckerbestie** [comment]
Naja ein paar Minuten warten dauert länger als App einmal neustarten^^
Wollte es ja nur melden, weiß ja dass es eine Beta ist :)

**Comment by TailsxKyuubi** [comment]
Dieses Problem besteht allgemein, wie ausführliche Tests von uns zeigen. Allerdings tritt dieser bei anderen Geräten normalerweise nicht auf. Da dort das nur passiert wenn man mindestens 3 Folgen durchskippt

**Comment by TailsxKyuubi** [comment]
@z8ckerbestie Ich habe einen Verbesserung umgesetzt welches dein Problem lösen kann. Auf Smartphones kann man den Bug scheinbar nicht mehr auslösen, aber wie das mit dem TV ist kann ich leider nicht direkt an einem echten Gerät testen.

**Comment by z8ckerbestie** [comment]
Vielen Dank, kann ich dann testen wenn es die nächste Version gibt 😊.

**Comment by TailsxKyuubi** [comment]
@z8ckerbestie Hier ist eine Version mit dem aktuellen Fix. Der Bug konnte von unserer Seite nicht mehr ausgelöst werden
[app.zip](https://github.com/TailsxKyuubi/inoffizielle-AoD-App/files/6178421/app.zip)

**Comment by z8ckerbestie** [comment]
Dankeschön, sehr schneller Support 😊. Ich teste das und gebe dann Feedback 👍

Update: schaut gut aus, kann jetzt auch weiter schauen ohne die App jedes Mal neu zu starten 👍 danke!
