### ISSUE TITLE
Android tv Verbesserung

### ISSUE THREAD

**Issue by ghost** [TailsxKyuubi/inoffizielle-AoD-App#28]
Ich habe gemerkt das wenn man auf dem Android tv den ich jetzt habe mit 4gb RAM auf einen Anime geht es oben wo das Titel Bild und die Beschreibung zu lesen ist es immer etwas ruckelt aber wenn man dann weiter unten ist hört es auf.

**Comment by ghost** [comment]
Vielleicht solltest du generell Mal versuchen das die App nicht so viel Ram frisst den man merkt es auch in den streams das es etwas ruckelt.

**Comment by TailsxKyuubi** [comment]
Das reine Android TV hat ein schlechtes RAM Management. Der größte RAM Verbrauch geht für den Player drauf und allein, die Tatsache, dass bei Android TV ein entsprechendes Problem aufgetaucht ist, wie die Abstürze durch mangeldem RAM, beweißt das schon. Das Problem konnte man auch mit Mühe auf Smartphones und Tablets triggern, aber das würde nur vor kommen wenn man es explizit versucht

**Comment by TailsxKyuubi** [comment]
Desweiteren kann es auch sein, dass die CPU von dem Android TV da auch Softwaredecoding versucht und daher das Ruckeln herkommt. Das ist bei 1080p und 1080p+ durchaus nicht ausgeschlossen, da dort settings verwendet werden, die unter anderem vom hardware decoding nicht abgedeckt sein könnten

**Comment by TailsxKyuubi** [comment]
> Ich habe gemerkt das wenn man auf dem Android tv den ich jetzt habe mit 4gb RAM auf einen Anime geht es oben wo das Titel Bild und die Beschreibung zu lesen ist es immer etwas ruckelt aber wenn man dann weiter unten ist hört es auf.

ich löse dieses Problem ganz einfach. Ich entferne die Animation und die App springt dann sofort auf den Punkt

**Comment by ghost** [comment]
> > Ich habe gemerkt das wenn man auf dem Android tv den ich jetzt habe mit 4gb RAM auf einen Anime geht es oben wo das Titel Bild und die Beschreibung zu lesen ist es immer etwas ruckelt aber wenn man dann weiter unten ist hört es auf.
> 
> ich löse dieses Problem ganz einfach. Ich entferne die Animation und die App springt dann sofort auf den Punkt

Warum nicht

**Comment by ghost** [comment]
> > > Ich habe gemerkt das wenn man auf dem Android tv den ich jetzt habe mit 4gb RAM auf einen Anime geht es oben wo das Titel Bild und die Beschreibung zu lesen ist es immer etwas ruckelt aber wenn man dann weiter unten ist hört es auf.
> > 
> > ich löse dieses Problem ganz einfach. Ich entferne die Animation und die App springt dann sofort auf den Punkt
> 
> Warum nicht 

Also mich würde es nicht stören.

**Comment by TailsxKyuubi** [comment]
https://github.com/TailsxKyuubi/inoffizielle-AoD-App/commit/f8a21093db2290a6633846ef049d046e5764a5a3
