### ISSUE TITLE
Visueller Vorschlag für Android tv.

### ISSUE THREAD

**Issue by ghost** [TailsxKyuubi/inoffizielle-AoD-App#29]
Hi hab nen vorschlag für das App Icon auf Android TV denn es sieht halt aus wie auf dem Handy, ist zwar Ansich nichts schlimmes aber auf Android tv sind die Icon Quadrate deswegen sieht es ein wenig blöd aus den das Icon ist in der Mitte und der Rest ist von system blau ausgefüllt deswegen wäre es nice day was neues zu kreieren.

**Comment by TailsxKyuubi** [comment]
kannst gerne ein neues designen und einreichen

**Comment by ghost** [comment]
Ok versuche ich Mal muss kannst du mir die Farben Präfixe schicken, und muss unbedingt unoffiziel draufstehen und muss es ein bestimmtes Datei Format sein?

**Comment by TailsxKyuubi** [comment]
ja inoffiziell muss drinstehen, Vorzugsweise png als format

**Comment by ghost** [comment]
> ja inoffiziell muss drinstehen, Vorzugsweise png als format

Ok

**Comment by ghost** [comment]
Ne Frage hab gerade im Internet nach geschaut wie die size für das Android tv app icon sein soll und da steht dass das Bild im xhdpi Format sein soll.

**Comment by ghost** [comment]
> Ne Frage hab gerade im Internet nach geschaut wie die size für das Android tv app icon sein soll und da steht dass das Bild im xhdpi Format sein soll.

Verstehe das nicht so ganz.

**Comment by TailsxKyuubi** [comment]
Das wird nachher umgewandelt. Darum musst du dir keine Sorgen machen. Es sollte halt nur die gleiche höhe und breite haben

**Comment by TailsxKyuubi** [comment]
1000x1000 sollte als Ausgangsgröße passen

**Comment by ghost** [comment]
> Ne Frage schaue hab gerade im Internet nach geschaut wie die size für das Android tv app icon sein soll und da steht dass das Bild im xhdpi Format sein soll.

OK. Welches Programm entfielst du mir habe die creative cloud vpn adobe. Welches Programm eignet sich gut für App Icons.

**Comment by S0T0N0** [comment]
> 1000x1000 sollte als Ausgangsgröße passen

![Screenshot_20210323_212919_com.opera.browser.jpg](https://user-images.githubusercontent.com/72794819/112213885-dd060980-8c1e-11eb-99c1-8d874dcd84bc.jpg)

Sicher da steht 320x180

**Comment by TailsxKyuubi** [comment]
Du könntest theoretisch auch MS Paint verwenden. Hauptsache du kommst mit dem Programm klar und das kannst was du brauchst

**Comment by TailsxKyuubi** [comment]
> Sicher da steht 320x180

Die ganze App Icon Konfiguration mache ich nicht manuell. Das gibts schon fertige Lösungen um das automatisch zu machen. Das wandelt das alles passend um.

**Comment by ghost** [comment]
> > Sicher da steht 320x180
> 
> Die ganze App Icon Konfiguration mache ich nicht manuell. Das gibts schon fertige Lösungen um das automatisch zu machen. Das wandelt das alles passend um.

Ok.

**Comment by ghost** [comment]
> Du könntest theoretisch auch MS Paint verwenden. Hauptsache du kommst mit dem Programm klar und das kannst was du brauchst

Ich werde Illustrator versuchen zu nutzen.

**Comment by ghost** [comment]
Wie viel ppi soll das Bild haben?

**Comment by S0T0N0** [comment]
![AOD](https://user-images.githubusercontent.com/72794819/112223333-0d9f7080-8c2a-11eb-9d83-607a48a7358c.png)
Hab das fürs erste nur gemacht.

**Comment by ghost** [comment]
Welche font hast du für das AOD benutzt auf der handy ver.?

**Comment by TailsxKyuubi** [comment]
Die Standardfont die von Flutter verwendet wird, ist Roboto und wird an den meisten Stellen verwendet

**Comment by TailsxKyuubi** [comment]
> Wie viel ppi soll das Bild haben?

da hab ich keine konkreten Ansprüche

**Comment by ghost** [comment]
![AOD](https://user-images.githubusercontent.com/72794819/112289927-06f71480-8c8f-11eb-86ab-3a71f4061ee6.png)
wie schaut das für dich aus?

**Comment by ghost** [comment]
Habs im 1000 x 1000 pixel format gemacht.

**Comment by TailsxKyuubi** [comment]
> wie schaut das für dich aus?

Kurz gesagt nicht gut. Hier die Punkte nach kurzer Begutachtung:
1. Die Abstände sind inkonsistent
2. Du hast für die normale Schrift zwei verschiedene Schriftarten benutzt
3. das O und das D von der Pixel Grafik sind zu schwer als solche zu erkennen
4. Die Abstände nach laußen sind viel zu groß auf dem fernseher würdest du die schrift nicht mehr erkennen
5. Der schwarzton den du als hintergrund hergenommen hast wird bei fernsehern praktisch nicht verwendet. Hier wäre eine Alpha Ebene besser gewesen oder ein mattes schwarz
6. Farblich hat es kaum was mit der app zu tun

**Comment by ghost** [comment]
> > wie schaut das für dich aus?
> 
> Kurz gesagt nicht gut. Hier die Punkte nach kurzer Begutachtung:
> 1. Die Abstände sind inkonsistent
> 2. Du hast für die normale Schrift zwei verschiedene Schriftarten benutzt
> 3. das O und das D von der Pixel Grafik sind zu schwer als solche zu erkennen
> 4. Die Abstände nach laußen sind viel zu groß auf dem fernseher würdest du die schrift nicht mehr erkennen
> 5. Der schwarzton den du als hintergrund hergenommen hast wird bei fernsehern praktisch nicht verwendet. Hier wäre eine Alpha Ebene besser gewesen oder ein mattes schwarz
> 6. Farblich hat es kaum was mit der app zu tun

Ich bin was Design angeht nicht wirklich der beste.

**Comment by S0T0N0** [comment]
Ich weiß leider nicht wie groß das ganze denn sein soll kannst du mir eine schriftgrösse nennen die dafür geeignet ist.

**Comment by S0T0N0** [comment]
Ach und ich habe dir Font nicht gefunden.

**Comment by S0T0N0** [comment]
Und welchen Grauton hast du verwendet.
