### ISSUE TITLE
Angst

### ISSUE THREAD

**Issue by Vincent1243** [TailsxKyuubi/inoffizielle-AoD-App#30]
is:issue is:open ich hab irgendwie schiss das das Abzocke ist hab mir die App runtergeladen und musste Passwort eingeben also die app sieht super aus klar gibt's bestimmt was was man verbessern kann aber egal und habe angst das mein handy jetzt für arsch gehen wird oder mein Abo oder Bankdaten durch das passwort gehackt werden 

Aber an sich ist die App gut aber habe wirklich angst

**Comment by ghost** [comment]
Also ich kann dir vielleicht nicht die Angst nehmen aber ich kann dir sagen das die App sehr gut ist und nicht den Eindruck macht das die Login Daten geklaut werden ich nutze die App schon seit ca einem monat, natürlich gibt es hier und da noch einige Sachen die verbessert werden müssen aber alles im allen sehr gut.

**Comment by Letsplaybar** [comment]
Wenn man sich den Code anschaut gehen nur Anfragen an den Server von AoD weshalb diese Angst unbegründet ist, die Daten werden nur auf deinen Handy verarbeitet und auf den Servern von AoD selbst also auch nicht anders als wenn du auf die Website von AoD gehst, nur das es sich um einiges Leichter mit der App steuern lässt auf dem Handy und den PC.

**Comment by Vincent1243** [comment]
> Wenn man sich den Code anschaut gehen nur Anfragen an den Server von AoD weshalb diese Angst unbegründet ist, die Daten werden nur auf deinen Handy verarbeitet und auf den Servern von AoD selbst also auch nicht anders als wenn du auf die Website von AoD gehst, nur das es sich um einiges Leichter mit der App steuern lässt auf dem Handy und den PC.

Woher weißt du das es die selben Server von AOD sind wissen die von der app hier

**Comment by TailsxKyuubi** [comment]
Im Quellcode ist die Domainadresse von AoD fest im Quellcode verdrahtet. Die App nimmt aktuell nur Kontakt mit den AoD Servern. Die App wird noch durch den kommenden Updatecheck einmal beim Start noch einmal Kontakt mit Github aufnehmen um die aktuelle Version zu ermitteln mehr ist da aber nicht.

**Comment by Vincent1243** [comment]
Also nicht schlimm die App passiert da nichts

TailsxKyuubi ***@***.***> schrieb am Mo., 29. März 2021,
20:23:

**Comment by TailsxKyuubi** [comment]
Bitte entferne da

**Comment by Vincent1243** [comment]
Was?


TailsxKyuubi ***@***.***> schrieb am Mo., 29. März 2021,
21:08:

**Comment by TailsxKyuubi** [comment]
Closed heißt das Issue ist abgeschlossen
