### ISSUE TITLE
Pausieren und Vor/Zurückspulen

### ISSUE THREAD

**Issue by SebaZi** [TailsxKyuubi/inoffizielle-AoD-App#31]
Hey ich habe deine App gefunden und habe sie auf meinem Mi Stick installiert und muss sagen bin echt begeistert :) läuft um längen besser als die Crunchyroll App haha.
Als Verbesserungsvorschlag (falls du nicht schon daran Arbeitest) wäre es cool wenn es die Funktion gäbe den Stream zu pausieren oder die Funktion Vor/Zurückspulen zu können.

Mfg Seba

**Comment by TailsxKyuubi** [comment]
Es gibt die funktion bereits, allerdings kann es sein, dass die auf tasten gelegt ist, die deine fernbedienung nicht hat

**Comment by TailsxKyuubi** [comment]
Um diese zu ergänzen bräuchte ich ein foto deiner fernbedienung

**Comment by SebaZi** [comment]
Hier ein Bild von Amazon da ich nicht Zuhause bin :) 

![AB1F3101-DB3C-47A3-9461-566FB4085F21](https://user-images.githubusercontent.com/82126382/114079430-7a616e80-98aa-11eb-9170-a92d6bb91d66.png)

**Comment by TailsxKyuubi** [comment]
Ok. Es hätte ausgereicht,  wenn du geschrieben hättest, dass du ein Xiaomi mi benutzt. Ich steh damit ein wenig auf kriegfuß, da das einfach ne billige Kopie des Fire TV Sticks ist und der hersteller einfach zu dumm ist selbst die Vorspultasten auf die Fernbedienung einzubauen

**Comment by SebaZi** [comment]
Achso verstehe dann lässt sich scheinbar leider nicht wirklich was machen. Trotzdem danke für die Antwort

**Comment by TailsxKyuubi** [comment]
Der FireTV hat zwar auch nicht alle tasten die, die App beherrscht aber mit dem bist du besser dran als mit den Android TV Sachen von Xiaomi

**Comment by SebaZi** [comment]
Schade  Marmelade, trotzdem vielen dank dann schau ich die Folgen am Stück, bleibt mir ja nichts anderes übrig. Wahrscheinlich lässt sich mit dem Steuerkreuz und dem Knopf in der Mitte auch nichts machen.

**Comment by TailsxKyuubi** [comment]
an sich schon, aber meine angst dabei ist, dass der fokus im player ins irgendwo springt und dann keine der tasten mehr funktioniert. war auch einer der probleme während der entwicklung allgemein

**Comment by SebaZi** [comment]
Verstehe ja das hört sich natürlich wirklich Problematisch an. Wär natürlich scheisse wenn der „Cursor“ irgendwo im void ist

**Comment by TailsxKyuubi** [comment]
Es wurde implementiert innerhalb des Players und wird Teil der 0.8 sein. Vorab versionen sind auf dem Gitlab verfügbar
