### ISSUE TITLE
Design Vorschlag

### ISSUE THREAD

**Issue by tyl0re** [TailsxKyuubi/inoffizielle-AoD-App#35]
ich hoffe ich geh dir nicht auf die Nerven mit Vorschlägen, (Hoffe es ist o.k das  ich soviel anbringe)

Das Menu (Starteite,Anime,Einstellungen) entweder Oben, oder an der Seite anzeigen und nicht Unten.
Unten hat den Nachteil das wenn man einen Anime Sehen will erst durch alle Kanäle nach unten durch muss

**Comment by TailsxKyuubi** [comment]
Ursprünglich war ja nur die menü taste dafür vorgesehen, allerdings da es hersteller gibt die der meinung sind, dass die menü taste überflüssig ist, hatte ich auf die schnelle die möglichkeit implementiert. ich hatte mir auch überlegt, da abkürzungen zu reinzuprogrammieren, aber da ist leider noch keine gute idee gekommen. Das menüwird da unten bleiben, da das designtechnisch und codetechnisch sonst ein flickteppich wird.

**Comment by tyl0re** [comment]
Hab mal geschaut obs ne andere Lösung gibt:
Netflix : Menu Links
Youtube: Menu Links
Amazon: Oben
Disney: Oben
Kividoo: Oben
MagentaTV: Oben
TVNow: Links
Wakanim: Links
Twitch: Oben
ARD: Links

Einige Apps haben ne weiteren Ansatz: der Back Knopf auf der Startseite bringt einen ins Menu und erst danach beendet er die App Für ein Schnelles Wechseln ins Menu, Das ist meist mit Oben oder Links kombiniert.

**Comment by TailsxKyuubi** [comment]
Eine Idee meinerseits während der Entwicklung war auch dass wenn man rechts und links in ne andere zeile springen würden, dass stattdessen man ins menü springt. die idee wurde aber verworfen
