### ISSUE TITLE
Markierung eines Kästchen geht manchmal Verloren

### ISSUE THREAD

**Issue by tyl0re** [TailsxKyuubi/inoffizielle-AoD-App#36]
Bei AndroidTV
Fehler kann reproduziert werden durch:
1. Man wählt Neue Anime Titel aus. Geht dort 6 nach Rechts
2. Nun Runter Druecken auf Anime TOp10
3. Geht nun wieder zurück auf  "Neue Anime Titel" dann geht zurück Auf das Erste Element , verliert aber die Makierung (Gruener Ramen)

Nicht wichtig, dachte nur ich schreibe mal, hoffe das ist o.k

**Comment by TailsxKyuubi** [comment]
Müsste ich mir nochmal genauer anschauen, aber nach deinem weiteren tastendruck in der navigation findet der doch den rahmen dann wieder richtig oder?

**Comment by tyl0re** [comment]
Ja der nächste Tastendruck ist dann wieder da. Insofern eher nen Schönheitsfehler
