### ISSUE TITLE
GitLab Frage

### ISSUE THREAD

**Issue by ghost** [TailsxKyuubi/inoffizielle-AoD-App#37]
Wie kann man sich die vorab Ver. auf GitLab runterladen?

**Comment by Letsplaybar** [comment]
In dem man unter https://git.tailsxkyuubi.moe/tailsxkyuubi/inoffizielle-AoD-App/-/pipelines auf den Letzten Build geht bis man auf den Log kommt
![image](https://user-images.githubusercontent.com/20257680/114238205-87eb2700-9984-11eb-8596-6408e653aa84.png)
![image](https://user-images.githubusercontent.com/20257680/114238237-976a7000-9984-11eb-9545-46b38823b567.png)

dann auf Browse auf der Rechten Seite klicken und die Ordnerstruckture runter klicken.
![image](https://user-images.githubusercontent.com/20257680/114238341-be28a680-9984-11eb-82d2-7331811ee4c9.png)

bis es so aussieht:
![image](https://user-images.githubusercontent.com/20257680/114238401-d698c100-9984-11eb-90ff-42a07a76df85.png)
dann auf den Markierten Teil klicken und der Download startet.

**Comment by Letsplaybar** [comment]
auf dem FireTV/ Android TV kommt man auf die pipline site über den Tag v0.8 und dann neben dem commit das selbe Symbol wie oben im ersten Bild was markiert ist sonst alles gleich.
