### ISSUE TITLE
Android tv back button Im menü

### ISSUE THREAD

**Issue by ghost** [TailsxKyuubi/inoffizielle-AoD-App#41]
Was fine Überlegung wert währe ist das Mann den zurück Knopf so auslegt das man damit nicht die App beenden kann sondern das Mann auch zurück auf die Start Seite kann. Mann muss sonst nämlich immer die App neu starten wenn Mann auf die Start Seite will nachdem Mann auf der Anime Seite war.

**Comment by Letsplaybar** [comment]
man kann auch übers menü auf die Startseite gehen xD muss nicht die app schließen und wieder öffnen xD

**Comment by ghost** [comment]
Wie denn bei mir hat's nicht geklappt.

**Comment by Letsplaybar** [comment]
Das man mit der Zurücktaste die App schließen kann und nicht nur in den Hintergrundverschieben kann (was man mit der Home taste machen würde) ist schon wichtig grade bei Vorabversionen wo man sonst nicht mehr aus Fehlern rauskommen könnte.

**Comment by Letsplaybar** [comment]
> Wie denn bei mir hat's nicht geklappt.

also ich klicke auf die Menü taste und dann gehe ich auf den Punkt Startseite geht sowohl auf der Anime als auch auf der Einstellungsseite. Auf der Episodenübersicht gehe ich ja einen schritt zurück so das ich aufs menü wieder komme

**Comment by ghost** [comment]
> > Wie denn bei mir hat's nicht geklappt.
> 
> also ich klicke auf die Menü taste und dann gehe ich auf den Punkt Startseite geht sowohl auf der Anime als auch auf der Einstellungsseite. Auf der Episodenübersicht gehe ich ja einen schritt zurück so das ich aufs menü wieder komme

Meinst Android tv oder Amazon fire tv stick?

**Comment by Letsplaybar** [comment]
beim AndroidTV muss halt nach ganz nach unten scrollen dann kommst auch ins menü dauert leider etwas beim Firetv hast halt die Menü taste die an die App weitergegeben wird als abkürzung.

**Comment by Letsplaybar** [comment]
dazu ist der Issue nen Duplication vom issue #35
