### ISSUE TITLE
Android TV Fehler Steuerkreuz.

### ISSUE THREAD

**Issue by ghost** [TailsxKyuubi/inoffizielle-AoD-App#42]
Wenn man den linken Steuerkreuz Knopf drückt spult man vor, wenn man den rechten Steuerkreuz Knopf drückt spult man vor, wenn man den mittleren Knopf drückt passiert nichts.

**Comment by TailsxKyuubi** [comment]
Auf dem FireTV scheint das Steuerkreuz richtig zu funktionieren und die Mi Sticks sind keine richtigen Android TVs. Sie sind Kopien vom FireTV mit Android und daher auch eine eigene Produktlinie die meinerseits nicht direkt unterstützt wird

**Comment by ghost** [comment]
> Auf dem FireTV scheint das Steuerkreuz richtig zu funktionieren und die Mi Sticks sind keine richtigen Android TVs. Sie sind Kopien vom FireTV mit Android und daher auch eine eigene Produktlinie die meinerseits nicht direkt unterstützt wird

Ums genau zu sagen sind die Mi Sticks/Boxen originale Android tv's der fire tv stick ist kein Android TV das hört man schon am Namen fire tv mich android tv also sind die Mi Sticks/Boxen keine Kopien sondern etwas ganz anderes denn das OS unterscheidet sich im großen von einander.

**Comment by TailsxKyuubi** [comment]
Den Testberichten nach zu Urteilen nicht. ich selbst habe nur die  Möglichkeit in einer virtuellen Maschine mit einem Clean Android TV zu testen. Fire TV wird durch Letsplaybar getestet. Ich habe keine Möglichkeit den Support von der Mi Reihe zu testen.
Allein der FireTV ist da eigentlich schon sehr problematisch, allerdings hält sich dieser an die Standards und ist auch fürs Streaming gemacht, was ich bei den Mi Geräten anzweifle. Das Android TV Betriebssystem wurde ursprünglich rein für Fernseher gemacht, jedoch hatte Amazon die Marktlücke erkannt dass man doch auch Fernsehern die keine Smart-TVs sind die funktionen eines Smart-TVs geben kann indem man Android TV auf nen HDMI Stick haut. Von dem her sind FireTV als auch die Mi Geräte keine Android TVs im eigentlichen Sinn
