### ISSUE TITLE
Download Funktion

### ISSUE THREAD

**Issue by Toaster99** [TailsxKyuubi/inoffizielle-AoD-App#43]
Wäre es möglich eine Download Funktion hinzufügen so das man die folgen herunterladen kann, um sie dann unterwegs gucken zu können? Soweit ich weiß hat AoD ja keinen Kopierschutz was heißen würde das es als Privatkopie zählen würde und somit auch Legal wäre.

**Comment by TailsxKyuubi** [comment]
Ich bin mir bewusst, dass sich viele dieses Feature wünschen. Da es allerdings gegen die AGB von AoD verstößt, kann ich zusichern dass solange keine direkte Erlaubnis seitens AoD für dieses Feature vorliegt, das nicht kommen wird solange die App inoffiziell ist.

**Comment by Toaster99** [comment]
Das ist schade. Das heißt dann wohl das wir noch ein paar Jahre warten müssen, falls eine offizielle App dann irgendwann überhaupt mal kommt.
