### ISSUE TITLE
Neue Ver.

### ISSUE THREAD

**Issue by ghost** [TailsxKyuubi/inoffizielle-AoD-App#45]
Hi wollte fragen wie lange es ungefähr dauert bis die nächste ver. oder ein neues update kommt.

**Comment by TailsxKyuubi** [comment]
In der letzten Zeit hatte ich leider privat einige andere Sachen zu erledigen und kam nicht dazu die neuen Features zu implementieren. Es kommt evtl. ein Bugfix Update, kann aber dazu nichts genaueres sagen.
