### ISSUE TITLE
Video spielt langsamer ab als Audio

### ISSUE THREAD

**Issue by ghost** [TailsxKyuubi/inoffizielle-AoD-App#48]
Hey Zusammen,
ich hab immer wieder das Problem, dass während dem anschauen einfach Mal kurz das Video langsamer wird aber der Ton normal weiter läuft. Also ist der Ton dann komplett asynchron. Wenn man dann aber vor oder zurück spult passt es wieder.  Passiert manchmal alle paar Sekunden aber dann auch Mal wieder eine oder zwei Folgen gar nicht.
Vielleicht weiß ja wer woran es liegt

**Comment by TailsxKyuubi** [comment]
Klingt mir stark danach, dass dein Gerät nicht leistungsstark genug ist um das Video flüssig zu decodieren. Ich gehe mal davon aus, dass du 1080p oder 1080p+ als Qualität ausgewählt hast.

**Comment by ghost** [comment]
Habe jetzt auch die verschiedenen Auflösungen ausprobiert aber passiert immer noch. Hatte davor aber auch noch nie Performance-Probleme bei irgendetwas.

**Comment by TailsxKyuubi** [comment]
Es könnte theoretisch auch sein, dass der Arbeitsspeicher verdammt voll ist von anderen Apps oder Android selbst.
Es könnte sein, dass irgendwelche Apps im Hintergrund den Handyprozessor so stark belasten. Es gibt so viele Gründe was es sein könnte. Ich weiß ja noch nicht mal welches Modell du hast, damit ich vielleicht irgendetwas aus den tecchnischen Spezifikationen lesen kann.

**Comment by TailsxKyuubi** [comment]
Keine Antwort mehr gekommen, daher wird das Issue geschlossen
