### ISSUE TITLE
Tab für gekaufte inhalte

### ISSUE THREAD

**Issue by ghost** [TailsxKyuubi/inoffizielle-AoD-App#49]
Hi es wäre nice wenn du einen Tab einführen würdest wo man seine gekauften inhalte sehen kann.

**Comment by TailsxKyuubi** [comment]
Meines wissens nach werden gekaufte Inhalte aktuell einfach in der Ansicht "Meine Animes" bei AoD gelistet. Daher werden diese mit denen aus dem Abo in der Übersicht kombiniert. Oder liege ich da irgendwie falsch?

**Comment by ghost** [comment]
Stimmt schon aber so ein Tab wäre schon nice für Leute ohne Abo

**Comment by TailsxKyuubi** [comment]
Ichb habe mir das ganze mal angeschaut und aktuell wird das aus zwei Gründen nicht implementiert:
1.  Die App kann als Abonnent nicht unterscheiden was gekauft ist und was nicht. Somit fehlt die klare Datenbasis
2. Es muss wieder einiges beim Abholen der Daten umgebaut werden und auch bei der Darstellung
