### ISSUE TITLE
Spende??

### ISSUE THREAD

**Issue by Midniight1122** [TailsxKyuubi/inoffizielle-AoD-App#6]
Hey, ich find deine Arbeit echt super, gibt es eventuell ne Möglichkeit für dieses Projekt zu spenden? 👍

**Comment by TailsxKyuubi** [comment]
Aktuell nicht. Wenn du das Projekt unterstützen willst, ist es sinnvoller mehr Leute von der App zu überzeugen. Das Ziel der App istes langfristig zur offiziellen aufzusteigen. Aufgrund der Situation mit Crunchyroll US ist die ganze Situation um einiges schwieriger.

**Comment by Midniight1122** [comment]
Bereits gestern habe ich zwei Leuten die App empfehlen können, dann werde ich dies auch weiterhin tuen. :) Diese App ist wirklich angenehmer als die Kodi-Variante. :)
