### ISSUE TITLE
Verbesserungsvorschläge

### ISSUE THREAD

**Issue by xScinnex** [TailsxKyuubi/inoffizielle-AoD-App#7]
Ich weiß nicht ob das hier der richtige Bereich ist, aber Ich schreibs trotzdem mal hier :D.
Ich nutzte die App jetzt schon seit ein paar Tagen relativ aktiv und mir sind einige Dinge aufgefallen die man für den Komfort etc. anpassen könnte.
(Vorab möchte Ich sagen das Ich keine Ahnung von dem Umfang der Arbeit habe die es Benötigt sowas zu ändern oder einzufügen)
1. Das Feature das der Folgenfortschritt gespeichert wird ist geil, jedoch kann man in der App nicht sehen welche Folgen man bereits geschaut hat.
2. Im gleichen Atemzug könnte man den grünen Playbutton den man erhält wenn man auf der Seite der Serie ist dafür nutzen um bei der zuletzt angesehen Folge weiterzumachen.
3. Der Player selbst ist solide, jedoch ist die Lautstärkesteuerung so wie sie ist störend. Ich hab ein Samsung S9+, bei mir faded die Menüleiste im Player aus d.h. wenn ich den Infoleiste oder die Menüleiste mit der rechten Hand reinswipe ändere Ich jedes mal die Lautstärke. Deswegen vllt. einen Button dafür oder eine andere Steuerung.
4. Man könnte den +30sek. Button in einen +90sek. Button ändern. So könnte man die meisten Intros sofort überspringen.

**Comment by TailsxKyuubi** [comment]
Ja das ist der richtige Bereich.
Zu deinen Punkten:
1. Dazu hatte ich mir bereits gedanken gemacht. Jedoch ist das bisher ausgeblieben, da ich keine gute idee hatte wie man das optisch gut darstellen könnte.
2. Das kam schon mal von anderer seite als kritikpunkt. so war der button auch angedacht, nur aktuell wird die entscheidung getroffen welche folge dann genau abgespielt wird, beim Laden der Episodenübersicht. Das wird mit der Version 0.8 verbessert.
3. Ich hatte mich dabei an anderen Player orientiert. wie z. B. MX Player oder den VLC. Ich könnte es auch implementieren, dass man den Playerinternen lautstärke regler in den Einstellungen deaktivieren kann.
4. Ich habe auch schon manchmal mit dem Gedanken gespielt, die Leiste mit den Buttons mal etwas umzugestalten. Aber konkreteres habe ich noch nicht. Für Designvorschläge bin ich immer offen und können ja hier auf Github gepostet werden.

Für die Version 0.8 soll auch der Support für Android TV und Fire TV fertig werden. daher dauert es etwas bis ich mich an die anderen Themen von 0.8.0 setzen kann

**Comment by Letsplaybar** [comment]
zu 4. finde ich 90s skip schon zu viel da sind 30s schon ganz gut gewählt und 3x draufdrücken fürs intro sollte wohl auch gehen.

**Comment by xScinnex** [comment]
Hm, wird dann wahrscheinlich was subjektives sein.
Jedoch wüsste Ich keine normale Situation  in der Ich einen +30sek Button verwenden würde außer um das Intro zu überspringen, deswegen dachte ich wär auch ein +90sek Button nicht schlecht.
(Außerdem hat das 3 mal schnell auf +30sek drücken bei mir öfters die App gecrasht :D)

**Comment by TailsxKyuubi** [comment]
Die App Crashes schaue ich mir gerne an. Eine Vermutung habe ich schon woran das liegen könnte

**Comment by TailsxKyuubi** [comment]
@xScinnex ich konnte den Crash der App leider nicht replizieren hoffe aber, dass mit dem aktuellen update bei dir das auch behoben ist.

**Comment by xScinnex** [comment]
Kann auch sein das die App in dem Moment sowieso gecrashed wär (durch irgendwelche anderen Einflüsse), Zufälle gibt's 🤷🏻‍♂️ 😁.
(Da Ich mich zugegebenermaßen nicht wirklich auf GitHub zurechtfinde, sry falls es irgendwo schon steht:)
Wollte nur draufhinweisen das das Problem mit der Lautstärke noch besteht.
= durch hereinswipen der Menü- und der Infoleiste des Telefons mit der rechten Hand (Rechtshänder) ändert man die Lautstärke unabsichtlich

**Comment by TailsxKyuubi** [comment]
Ja das ist für die version 0.8 vorgesehen

**Comment by xScinnex** [comment]
Gibt es irgendwie ne "Roadmap" oderso? Finde da irgendwie nichts :D.

**Comment by TailsxKyuubi** [comment]
Für 0.8 habe ich noch keine gemacht, da es bisher noch unklar war / ist, was man da noch alles sinnvolles einbauen kann

**Comment by websconan** [comment]
Gibt es auch die Möglichkeit iOS Support (inkl. Apple TV) zu adden?

**Comment by TailsxKyuubi** [comment]
Für iOS auf iPhones und iPads sollte der Code auch kompilierbar sein. Dazu müssten da nur ein paar Konfigurationshandgriffe im Code gemacht werden. Leider ist es mir nicht möglich Tests durchzuführen, da ich nicht die möglichkeit habe die Apps für iOS zu kompilieren (geht nur auf MacOS) noch es auf einem Apple Gerät zu testen. Zum Thema Apple TV: Um das darauf zu entwickeln, würde ich einen benötigen, was für mich aktuell finanziell nicht in Frage kommt, genauso wenig wie andere Apple Geräte.

**Comment by TailsxKyuubi** [comment]
@websconan und außerdem wie hast du dir vorgestellt die app ohne jailbreak auf dem iPhone zu installieren? Die App wird voraussichtlich erst dann in den App Store kommen, wenn diese zur offiziellen aufsteigt.

**Comment by TailsxKyuubi** [comment]
@xScinnex ist dein Anliegen soweit geklärt? Die roadmap ist auch hier auf github

**Comment by KILLERsandwich** [comment]
Eine amazon fireTv Version wäre echt top oder das diese auf dem fireTv funktioniert halt. habe es probiert auf gut Glück konnte nur Leider nichts steuern einloggen hat allerdings funktioniert

Und was ich Klasse fände wäre im Home Menü der App ein zusätzlicher Reiter der einem anzeigt welche Anime Serien mann zuletzt gesehen hat oder eine Favoriten Liste damit mann halt schneller an die Animes rankommt die man weiter schauen will 😄.

Was das anzeigen des Folgen Fortschritts angeht, hätte ich die Idee das man die Bilder der jeweiligen Folge einfach mit nem dicken grünen rand versehen könnte wenn sie angeschaut wurden finde das ästhetisch nicht schlecht oder halt wie auf der Seite ein kleines Logo mit nem hacken unten an die rechte Ecke des jeweiligen Bildes
(✅ )Sowas zum beispiel

Für den Player finde ich die Orientierung am MX Player echt gut es wäre noch optimal wenn man das spülen also das werschieben der Zeit genauso wie im MX Player durch das wischen am unteren Bildschirmrand implementieren könnte 😃 das würde das überspringen des Intros und so weitaus erleichtern außerdem wär's denke ich besser wenn die Anzeige für die Lautstärke schneller wieder verschwinden würde ich muss für meinen Geschmack ein bisschen zu lange warten bis sie wieder weg ist und die hitbox (ich hoffe Mal das heißt so) zum steuern der Lautstärke is zu groß die reagiert sogar wenn ich in der Mitte des Bildschirms hoch und runter schiebe ich denke die sollte weitaus kleiner sein.

Und zu guter Letzt fände ich es Klasse wenn die App fullscreen unterstützen würde also das die App und der Player den ganzen Bildschirm verwenden und nicht wegen einer notch oder einem Punchhole der Handy Kamera haufenweise Platz verloren geht.

So hoffe ich bin nicht zu fordernd ich bin überglücklich das jemand die Entwicklung der App in die eigenen Hände genommen hat da Aod das selbst wohl nicht hinbekommt 😃👍

**Comment by TailsxKyuubi** [comment]
Also das mit dem FireTV ist ja grade so, dass ich da aktuell dran sitze das umzusetzen. Das ist aber technisch etwas schwierig, daher zieht sich das.
Was mich eher wundert dass du meintest, dass die App nicht in den FullScreen Mode geht. kannst du da mal Bilder schicken? Weil eigentlich geht die App in den Full Screen Mode spätestens sobald du einen Stream startest

**Comment by KILLERsandwich** [comment]
Klar hier weiß nicht ob man das da richtig sieht. 😅
![Screenshot_20210220-120617](https://user-images.githubusercontent.com/79344628/108593540-9ea5d200-7374-11eb-9e5b-8e2714c4db3c.jpg)
![Screenshot_20210220-120514](https://user-images.githubusercontent.com/79344628/108593542-9fd6ff00-7374-11eb-88b4-0880989b6841.jpg)
![Screenshot_20210220-120438](https://user-images.githubusercontent.com/79344628/108593543-9fd6ff00-7374-11eb-8437-996e9ee57f6c.jpg)
![Screenshot_20210220-120431](https://user-images.githubusercontent.com/79344628/108593544-a06f9580-7374-11eb-8b1d-db6d76da6183.jpg)
Benutze ein oneplus 8t mit Android 11 und hab die die neuste Version der App vielleicht iss es Gerät spezifisch hab Grad festgestellt das das Menü im Prinzip Vollbild ist nur der Player nicht sobald ich jedoch den Player 1 Mal gestartet hab ist auch das normale Menü nichtmehr fullscreen

**Comment by TailsxKyuubi** [comment]
ich habe mir einen ersten überblick verschafft. der schwarze rand im ladescreen für das video kann ich nicht spontan sagen, was da genau passiert ist. aber die ränder im player drin sind normal aufgrund des bildschirms deines handys (das problem im ladescreen sein im player auch noch da zu sein). die meisten videos bei AoD haben das seitenverhältnis 16:9. Dein Gerät hat allerdings 20:9 und daher kommen die Ränder zustande, da sonst oben und unten etwas vom Video abgeschnitten wird

**Comment by KILLERsandwich** [comment]
Dachte mir das das auch am Seiten Verhältnis liegt der normale schwarze Rand allerdings ist das Bild dadurch daß es nicht im fullscreen Mode läuft etwas nach rechts verschoben was ein bisschen irritiert beim schauen, das ist jedoch meckern auf ganz hohem Niveau von mir also nicht so schlimm

**Comment by TailsxKyuubi** [comment]
Damit das hier nicht zu unübersichtlich wird schließe ich den Thread hiermal
